name: JimJohnson
favicon: null
layout_spectrum: 0.07548093097284436
typography_spectrum: 0.9656156410928816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9093695285264403
  lightness: 0.07680118852294981
  saturation: 0.9088484812527895
  rhythmicContrast: 0.47834036219865084
purpose: []
